version: '3.7'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Test12!@
      MYSQL_DATABASE: flightservices
  app:
    image: flightservices
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/flightservices
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test12!@
      SERVER_SERVLET_CONTEXT_PATH: /flightservices
